### ISSUE TITLE
Turkish Translation [Completed]

### ISSUE THREAD

**Issue by gokdumano** [ncase/anxiety#1]
Bu zorlu işi kendime görev edindim ve çevirinin bitirilmesini onurum saydım. Bu zorlu görev için gelecek her türlü yardım baş üstünde tutula ve böylesi güzel bir oyun mümkün oldukça çok kişi tarafından biline.

TL;DR There is a Turkish translator doing his job and looking for collaborators in this town

*It's really hard to complete the translation with my full school schedule, any help would be 
appreciated*

~https://github.com/gokdumano/anxiety~
https://gokdumano.github.io/forks/anxiety/index.html

(Translated/Checked)     [SceneName]
--------------------------------------------
(y/Y)     [scenes/act1.md]
(y/Y)     [scenes/act2.md]
(y/Y)     [scenes/act3.md]
(y/Y)     [scenes/act4.md]
(y/Y)     [scenes/credits.md]
(y/Y)     [scenes/intermission.md]
(y/Y)     [scenes/intro.md]
(y/Y)     [scenes/PROMO.md]

(Translated/Checked)     [ImageName]
--------------------------------------------
(y/Y)     [sharing/thumb.png]
(y/Y)     [sprites/about/cc0.png]
(y/Y)     [sprites/about/replay.png]
(y/Y)     [sprites/act4/callback.png]
(y/Y)     [sprites/credits/end_message.png]
(y/Y)     [sprites/credits/screens.png]
(y/Y)     [sprites/credits/starring.png]
(y/Y)     [sprites/credits/thanks.png]
(y/Y)     [sprites/intermission/youwin.png]
(y/Y)     [sprites/intro/intro_logo.png]
(y/Y)     [sprites/ui/fear_captions.png]
(y/Y)     [sprites/ui/preloader.png]

**Comment by efsinazenn** [comment]
Selamlar. Çeviri işlemine hala devam ediyor musunuz acaba?

**Comment by gokdumano** [comment]
> Selamlar. Çeviri işlemine hala devam ediyor musunuz acaba?

Okulun son yılı giriştim ama yardım edecek kimse bulamayınca bitiremedim. Çeviri ama hep aklımda kalmıştı, beraber çevirebiliriz sana da uyarsa?

**Comment by efsinazenn** [comment]
> > Selamlar. Çeviri işlemine hala devam ediyor musunuz acaba?
> 
> Okulun son yılı giriştim ama yardım edecek kimse bulamayınca bitiremedim. Çeviri ama hep aklımda kalmıştı, beraber çevirebiliriz sana da uyarsa?

Harika olur. fakat ben github yeni kullanmaya başladım ve bu işlerin nasıl ilerlediği hakkında hiçbir fikrim yok. Sadece bana ne yapacağımı söylersen ben harfi harfine uyarım. Eminim sana yardımım dokunur:)

**Comment by gokdumano** [comment]
Öncelikle [Github Desktop](https://desktop.github.com) indirebilirsen iş daha da kolaylaşır. 

**Giriş yaptıktan sonra sırasıyla**

1. Bendeki repo'yu kopyala. Kopyalama işlemi bittikten sonra iki seçenek gelmesi lazım, üstteki _değişiklikler gokdumano/anxiety_'ye kaydolacak seçeneğini seçmen gerek.

![image](https://user-images.githubusercontent.com/53919703/123451250-39920f80-d5e6-11eb-8710-d86b5523ee16.png)
![image](https://user-images.githubusercontent.com/53919703/123451413-444ca480-d5e6-11eb-8c59-2f6c8278ec79.png)

2. Bilgisayarına yüklenen dosyaların nereye kaydolduğunu buradan açabilirsin

![image](https://user-images.githubusercontent.com/53919703/123451677-680fea80-d5e6-11eb-9706-ab89ff760708.png)

3. Hangi belirtilen dosyaları burada iş bölümü yapıp çevireceğiz sonraki adımda. Örneğin ben scenes/act1.md'yi notepad++ ile açtım ve sağdaki gibi bir satırı çevirdim.

![image](https://user-images.githubusercontent.com/53919703/123451915-9a214c80-d5e6-11eb-96c6-09f46543a957.png)

4. Github Desktop'a dönersen dosyada değişiklik yaptığını program farkedecektir. Önce **commit** sonra **push-origin** yaparsan bendeki dosyalar da değişecektir. Başkasının repo'sunu değiştirmek için izin gerekiyor, seni ekledim değişiklik yapabilecekler listesine. Bildirim gelmesi lazım. Her değişiklik yaptığında sol aşağıdaki özet ve açıklama kısmını doldurursan ne olup bittiğini takip edebiliriz, açıklama şart değil.

![image](https://user-images.githubusercontent.com/53919703/123452279-ee2c3100-d5e6-11eb-9880-8b74618b9687.png)

**Comment by efsinazenn** [comment]
Teşekkürler. Hepsini yaptım ve deneme amaçlı scenes act1 dosyasının ilk repliğini çevirdim. Umarım herhangi bir sorun yoktur. eğer tamamsa dosyaları aramızda bölümlendirebiliriz.

**Comment by gokdumano** [comment]
> Teşekkürler. Hepsini yaptım ve deneme amaçlı scenes act1 dosyasının ilk repliğini çevirdim. Umarım herhangi bir sorun yoktur. eğer tamamsa dosyaları aramızda bölümlendirebiliriz.

Tamamdır gördüm ben de değişiklik yaptığını. Ufak dosyaları ben çevirdim asıl büyük baş dosyalar Act'lar.

Satır sayılarına baktım eşit dağıtım olsun diye, Act1(1653 satır) ve Act2(1753) dosyalarına ben bakarsam, sen de Act3(1212 satır) ve Act4(1998 satır) dosyalarını çevirirsen başlayabiliriz bence. 

İlk çeviri kısmını bitirdikten sonra kontrol aşamasında terimleri ortak kullanıp kullanmadığımıza bakarız. Sonra resimlerin düzenlenmesine geçeriz.

**Comment by gokdumano** [comment]
Metin editörü olarak ne kullanıyorsun, çünkü act1.md'deki Türkçe karakterler okunmuyor, encoding UTF-8 şeklinde ayarlı değilse onu değiştrebilir misin?

![image](https://user-images.githubusercontent.com/53919703/123468908-1160db80-d5fb-11eb-9955-8815b06a5fe7.png)

![image](https://user-images.githubusercontent.com/53919703/123468795-efffef80-d5fa-11eb-973f-30bfda9f756c.png)

**Comment by efsinazenn** [comment]
> Metin editörü olarak ne kullanıyorsun, çünkü act1.md'deki Türkçe karakterler okunmuyor, encoding UTF-8 şeklinde ayarlı değilse onu değiştrebilir misin?
> 
> ![image](https://user-images.githubusercontent.com/53919703/123468908-1160db80-d5fb-11eb-9955-8815b06a5fe7.png)
> 
> ![image](https://user-images.githubusercontent.com/53919703/123468795-efffef80-d5fa-11eb-973f-30bfda9f756c.png)

Code Writer diye bir uygulamaya geçtim. Sanırım hallettim yine de bir bak. Bana verdiğin dosyaları da çevirmeye başlayacağım.

**Comment by gokdumano** [comment]
Ben de 27'sinden sonra başlayabileceğim, yaptığın değişikliği göremedim fakat düzenlemeni tekrar bendeki repo'dan kontrol edebilirsin.

**Comment by gokdumano** [comment]
Tüm bölümlerin çevirilerini yaptık gibi hepsini kontrol edeceğim bu akşam sonra resimlerin çevirilerini yaparız.

**Comment by efsinazenn** [comment]
> Tüm bölümlerin çevirilerini yaptık gibi hepsini kontrol edeceğim bu akşam sonra resimlerin çevirilerini yaparız.

Tamamdır. Ben de resim çevirisi için program bakacağım.

**Comment by gokdumano** [comment]
> > Tüm bölümlerin çevirilerini yaptık gibi hepsini kontrol edeceğim bu akşam sonra resimlerin çevirilerini yaparız.
> 
> Tamamdır. Ben de resim çevirisi için program bakacağım.

Çeviriyi kontrol etmek için resimlerin çevirisini yaptım, sonradan değiştirilebilir. [buradan](https://gokdumano.github.io/forks/anxiety/index.html) sen de ekrandan taşan yerleri not edersen en son kontrolde onları düzeltir Nicky'e e-posta atarız bitirdik diye.

1. Açılış ekranında başlık taşıyor
2. Oyun durdurulunca "durduruldu" yazısı taşıyor

gibi not alıyorum ben yavaş yavaş

**Comment by efsinazenn** [comment]
> > > Tüm bölümlerin çevirilerini yaptık gibi hepsini kontrol edeceğim bu akşam sonra resimlerin çevirilerini yaparız.
> > 
> > 
> > Tamamdı
> 
> Çeviriyi kontrol etmek için resimlerin çevirisini yaptım, sonradan değiştirilebilir. [buradan](https://gokdumano.github.io/forks/anxiety/index.html) sen de ekrandan taşan yerleri not edersen en son kontrolde onları düzeltir Nicky'e e-posta atarız bitirdik diye.
> 
> 1. Açılış ekranında başlık taşıyor
> 2. Oyun durdurulunca "durduruldu" yazısı taşıyor
> 
> gibi not alıyorum ben yavaş yavaş

Oyunu oynarken gözüme çarpan yazım hatalarını düzeltip tekrar gönderdim."Speak this fast" ve "on click" en başta ayar kısmında çevirilmemiş olduğunu gördüm. Bir de farenin üstünde "click or space bar" "tık ve boşluk" şeklinde çevrilmiş onu düzeltsek iyi olur. Onun haricinde resimlerin çevirisiyle ilgili bir sıkıntı göremedim. Diğer her şey yolunda görünüyor.

**Comment by gokdumano** [comment]
> > > > Tüm bölümlerin çevirilerini yaptık gibi hepsini kontrol edeceğim bu akşam sonra resimlerin çevirilerini yaparız.
> > > 
> > > 
> > > Tamamdır. Ben de resim çevirisi için program bakacağım.
> > 
> > 
> > Çeviriyi kontrol etmek için resimlerin çevirisini yaptım, sonradan değiştirilebilir. [buradan](https://gokdumano.github.io/forks/anxiety/index.html) sen de ekrandan taşan yerleri not edersen en son kontrolde onları düzeltir Nicky'e e-posta atarız bitirdik diye.
> > 
> > 1. Açılış ekranında başlık taşıyor
> > 2. Oyun durdurulunca "durduruldu" yazısı taşıyor
> > 
> > gibi not alıyorum ben yavaş yavaş
> 
> Oyunu oynarken gözüme çarpan yazım hatalarını düzeltip tekrar gönderdim."Speak this fast" ve "on click" en başta ayar kısmında çevirilmemiş olduğunu gördüm. Bir de farenin üstünde "click or space bar" "tık ve boşluk" şeklinde çevrilmiş onu düzeltsek iyi olur. Onun haricinde resimlerin çevirisiyle ilgili bir sıkıntı göremedim. Diğer her şey yolunda görünüyor.

O ayar arayüzünü ben de farketmiştim ilişkili dosyayı bulamamıştım, sen söyleyince tekrar aradım `scripts/game/Options.js` dosyasını çevirdim halloldu. 1-2 kere daha kontrol edip bitti diyebiliriz sanırım çeviriye.

**Comment by efsinazenn** [comment]
Nicky'den herhangi bir cevap geldi mi acaba?

**Comment by gokdumano** [comment]
7 Temmuz'da yazmıştım tatilde olduğunu söyleyen otomarik cevap gelmişti, hala bir dönüş yok 21'inde tekrar yazacağım.

**Comment by efsinazenn** [comment]
> 7 Temmuz'da yazmıştım tatilde olduğunu söyleyen otomarik cevap gelmişti, hala bir dönüş yok 21'inde tekrar yazacağım.

Tamamdır. Kabul edilince beni bilgilendirirsin. Teşekkür ederim.

**Comment by gokdumano** [comment]
Beklenen gün nihayet geldi @efsinazenn ! Çeviri artık orijinal oyunda linklendi, tebrikler ikimize de! 🎉🎈🎉🎈🎉

**Comment by efsinazenn** [comment]
> Beklenen gün nihayet geldi @efsinazenn ! Çeviri artık orijinal oyunda linklendi, tebrikler ikimize de!

Çok mutlu oldum, çok güzel bir çalışmaydı. Sana da her şey için çok teşekkürler<3
