### ISSUE TITLE
Pokemon song in translations

### ISSUE THREAD

**Issue by tezzutezzu** [ncase/anxiety#14]
Crazy idea: how about including the localized Pokemon theme for each country in each translation?

The emotional/comical value is a bit lost on me when using the American version.

We may run into some sort of copyright problems though. Maybe we could use a cover or even ask somebody to do a cover of it?

Here's the Italian opening theme if you're curious: 
https://www.youtube.com/watch?v=l4w7mevweXA

PS. best translation challenge so far :)

**Comment by ghost** [comment]
I used the original lyrics in Spanish , and changed them like I felt like thought I don’t know if I chose the right 4 sentences

**Comment by tezzutezzu** [comment]
Maybe I should just come up with an italian parody of the american theme song :)

**Comment by ghost** [comment]
Or use the lyrics of the Italian version and perv them , you choose

**Comment by lucasgcb** [comment]
The original game is already using it, I find it would fall under fair use in most circumstances specially since it isn't the whole track.

You might have to adjust the timing yourself in the markdown file if you throw in an instrumental version of the italian opening, since currently the speech balloons are timed with the tempo of the american one.

**Comment by ghost** [comment]
How can you test the scene? I just limited myself to traduce it so I couldn’t test that, I’m Totally new to this

**Comment by tezzutezzu** [comment]
@Aletuno You need to mimick a server that serves a web page. 

You can use tools such as MAMP or if you have a mac do the following:

- Open terminal
- Drag the folder 'anxiety' on the terminal icon in the dock
- In the terminal you should now be in the root of the folder. Now type:
```python -m SimpleHTTPServer 8000```

If you now go on your browser at the address http://localhost:8000 you should see the game

You can find more info [here](https://lifehacker.com/start-a-simple-web-server-from-any-directory-on-your-ma-496425450)
