### ISSUE TITLE
PT-BR Translation 

### ISSUE THREAD

**Issue by lucasgcb** [ncase/anxiety#2]
Olá aos brasileiros, traduzir esta obra será uma experiência interessante.  Eu já possuo experiência com localização de conteúdo e manipulação de imagens, logo estarei me disponibilizando para colaboração na tradução deste projeto aberto. 

Todos aqueles que se estiverem motivados em colaborar para trazer esta obra ao português brasileiro por favor me notifiquem nesta Issue. Gostaria de ao menos um revisor, mas podemos discutir qualquer divisão de tarefa caso houver interesse.

https://github.com/lucasgcb/anxiety
https://lucasgcb.github.io/anxiety/

Previsão da entrega: 23/09/2019

TL;DR: I will be translating this to PT-BR over the course of the current week, collaborators are welcome.

**Comment by Liz4v** [comment]
Boa tarde, posso revisar :)

**Comment by lucasgcb** [comment]
Olá, @ekevoo ! Você estaria disponível sexta, sábado ou domingo esta semana?

Outra pergunta, você é/foi de qual região do Brasil? Isso pode me ajudar bastante na questão de introdução/remoção de certas gírias já que atualmente estou levando o vocabulário informal da personagem em consideração.

**Comment by Liz4v** [comment]
Sexta sim, sábado provavelmente, domingo não.

Eu cresci em Porto Alegre (RS), morei 3 anos em Aracaju (SE), e 3 anos no Rio de Janeiro (RJ). Aqui em Toronto sou voluntário ativo de um centro espírita, o que me põe em contato constante com gente vinda de todo o Brasil.

**Comment by lucasgcb** [comment]
@ekevoo Opa, que beleza! Já temos ao menos 4 cantos aí de cobertura nacional.

Então, pra sexta já deve ter uma boa porção traduzida. Passei um tempinho agora de tarde colocando para rodar localmente, traduzindo o menu e alguns sprites.

Caso você se sinta ocioso neste meio tempo, [o repositório com os recursos de saúde emocional e mental](https://github.com/ncase/mental-health) seria legal traduzir também e vincular dentro do código. Poderia ser um fork seu (ou de quem mais se dispor), já que vou deixar lá pro final.

Se houver alguma preferência pelo meio de comunicação me avise, caso contrário ficarei dando ping aqui nesta issue mesmo.

**Comment by ncase** [comment]
Thank you all so much for helping translate!  Just so you know, I pushed a few more commits recently ( https://github.com/ncase/anxiety/commits/gh-pages , everything past "SHUT UP IT'S DONE"), that will slightly help with translation.

Specifically, `index.html` *actually* has notes on what to translate, there's a word-less version of the social sharing thumbnail, and the social sharing buttons can now be translated (as opposed to what it was earlier: the words directly url-encoded in the URL)

Hope that helps! :)

**Comment by LukanRocks** [comment]
Fala @lucasgcb tudo tanquilo? Eu gostaria de ajudar!

**Comment by lucasgcb** [comment]
Eae @lukanvanderlinde , suave na nave

Então, atualmente eu gostaria que alguém pudesse traduzir [o repositório com os recursos de saúde emocional e mental](https://github.com/ncase/mental-health) para vincular dentro dos diversos links no jogo. 

Enquanto ao grosso, sprites e cenas, já tá em andamento aqui. Hoje terminei o primeiro capítulo, que pode ser [jogado aqui](https://lucasgcb.github.io/anxiety/). Faltam alguns sprites ainda (tumba do celular e lago de lágrimas). Estou prevendo 1 capítulo por dia, amanhã (19/09) entrego o 2.  Se for possível passar o olho no que foi feito agora para ver se eu não fiz cagada ou falei besteira ficarei bem grato.

Se você tiver coçando _muito_ para traduzir parte do game a gente pode ver um workflow para traduzir o Capítulo 4.

Abraços

**Comment by vmarchesin** [comment]
Se precisar de um revisor posso ajudar também :) Não sei se terei tempo de ativamente traduzir, mas posso ajudar com uma revisão.

**Comment by LukanRocks** [comment]
> Eae @lukanvanderlinde , suave na nave
> 
> Então, atualmente eu gostaria que alguém pudesse traduzir [o repositório com os recursos de saúde emocional e mental](https://github.com/ncase/mental-health) para vincular dentro dos diversos links no jogo.
> 
> Enquanto ao grosso, sprites e cenas, já tá em andamento aqui. Hoje terminei o primeiro capítulo, que pode ser [jogado aqui](https://lucasgcb.github.io/anxiety/). Faltam alguns sprites ainda (tumba do celular e lago de lágrimas). Estou prevendo 1 capítulo por dia, amanhã (19/09) entrego o 2. Se for possível passar o olho no que foi feito agora para ver se eu não fiz cagada ou falei besteira ficarei bem grato.
> 
> Se você tiver coçando _muito_ para traduzir parte do game a gente pode ver um workflow para traduzir o Capítulo 4.
> 
> Abraços

Fechado!

**Comment by lucasgcb** [comment]
Olá @ekevoo @vmarchesin  boa tarde, a primeira versão até o capítulo 3 está feita e pode ser jogada [aqui](https://lucasgcb.github.io/anxiety/).

Até hoje acho que ainda sai o capítulo 4, então se tiverem como revisar o que já tem, ou ver tudo de uma vez amanhã (21/09), seria de bom proveito. 

Peço que prestem atenção na presença de gírias _muito_ regionais, pois sou do Sul e as vezes me escapa. Se tiverem sugestões e correções peço que ou me respondam aqui, ou façam um Pull Request do fork da tradução. Estou usando a branch do master para as alterações.

Abraços

**Comment by lucasgcb** [comment]
Oi @ekevoo , obrigado por estar realizando a revisão mas eu peço que faça um fork (do meu fork) e realize um PR com as alterações que você propõem pros capítulos adiantes. 

Você está colocando vários comentários em um commit antigo, o que é difícil de resgatar, e que também está estourando minhas notificações. Dessa outra maneira, a gente pode discutir melhor, e ao aceitar o PR aqui você já é marcado como colaborador do script automaticamente.

Abraços

**Comment by Liz4v** [comment]
Haha blz. Eu senti depois de um tempo que talvez não fosse o melhor approach.

**Comment by lucasgcb** [comment]
Oi @lukanvanderlinde , você tem como ativar o [seu github pages do repositório dos recursos](http://lukanvanderlinde.github.io/mental-health)?
Daí eu já posso colocar as referências pra URL no código, e então a última versão que você fizer aí já aparece na página.

Até amanhã a primeira versão inicial de tudo já saiu aqui.

Abraços

**Comment by LukanRocks** [comment]
> Oi @lukanvanderlinde , você tem como ativar o [seu github pages do repositório dos recursos](http://lukanvanderlinde.github.io/mental-health)?
> Daí eu já posso colocar as referências pra URL no código, e então a última versão que você fizer aí já aparece na página.
> 
> Até amanhã a primeira versão inicial de tudo já saiu aqui.
> 
> Abraços

Feito! Ativei o github pages do repo.

**Comment by lucasgcb** [comment]
Hello @ncase , the first full version of the Brazilian Portuguese (PT-BR) translation is out, and [can be played here](https://lucasgcb.github.io/anxiety/). It was very fun to do.

The Resources page is being translated by @lukanvanderlinde , and should be available soon from within the translated page.

Let us know if you need anything else.

Cheers

**Comment by vmarchesin** [comment]
@lucasgcb Comecei uma revisão por cima, vou deixar alguns comentários em commits antigos seus (que já não tenham sido corrigidos, claro).

Apesar da versão já estar pronta, disse que iria revisar mas acabei ficando sem tempo. Se achar interessante pode fazer as alterações depois.

**Comment by lucasgcb** [comment]
> @lucasgcb Comecei uma revisão por cima, vou deixar alguns comentários em commits antigos seus (que já não tenham sido corrigidos, claro).
> 
> Apesar da versão já estar pronta, disse que iria revisar mas acabei ficando sem tempo. Se achar interessante pode fazer as alterações depois.

Oi @vmarchesin , esta é apenas a primeira versão completa. O projeto sempre estará aberto para iterações, logo todos que acharem algo estranho ou muito errado ainda são bem vindos a propor mudanças.

O protocolo para revisões é através de Pull Request, [como eu havia mencionado](https://github.com/ncase/anxiety/issues/2#issuecomment-533829360) ao eekevo. Será bem mais fácil de discutir e alterar as coisas desta maneira. Apenas crie um fork (do meu fork), aplique as mudanças, e crie um PR.

Isso é justamente para não deixar esses comentários, pois são difíceis de resgatar, você não aparece como colaborador do script se a revisão for aprovada, e o fato dos commits serem antigos facilita com que você se engane e acabe por corrigir coisas que já foram arrumadas.

Abraços

**Comment by lucasgcb** [comment]
@ncase Re-ping after a week.

**Comment by ncase** [comment]
Hi hi @lucasgcb ! Sorry I missed this, it was buried in other Github notifications. (I changed the README to say peeps should just email me directly instead)

Thank you all so so so much for putting in the hard effort to translate this! It's officially linked to from the main page:

<img width="173" alt="Capture d’écran 2019-10-01 à 5 55 21 PM" src="https://user-images.githubusercontent.com/825858/66003803-12d89080-e475-11e9-9db7-223ae6258f81.png">

Muito obrigado! 💖

**Comment by jvschiavo** [comment]
Hey! First of all, thanks for taking your time to make the translation! Thanks to you a lot of friends of mine can now enjoy such experience. But I noticed quite a handful of small mistakes and would love to revise the text. But I'm not used to github (and specially git) besides creating issues and commenting issues of others. If someone would like to to help me with that I'd be able to submit my revision, and if others aprove it could be deployed. And I also would have learned something new. :)

**Comment by Liz4v** [comment]
Hi João. I can help you. My Gmail account is the same as my github account, just email me your contact info for your preferred option for sharing your screen.

**Comment by lucasgcb** [comment]
> Hey! First of all, thanks for taking your time to make the translation! Thanks to you a lot of friends of mine can now enjoy such experience. But I noticed quite a handful of small mistakes and would love to revise the text. But I'm not used to github (and specially git) besides creating issues and commenting issues of others. If someone would like to to help me with that I'd be able to submit my revision, and if others aprove it could be deployed. And I also would have learned something new. :)

Eaí João, beleza? Obrigado pela força!

Se quiser ajudar de um jeito mais fácil, basta tirar printscreen dos erros e compartilhar aqui, que daí eu dou uma olhada e arrumo.

Agora, se quiser ajudar usando o software git, que irá vincular seu nome como contribuidor do repositório de uma maneira mais oficial, você terá que fazer o seguinte:

1- Criar a Conta no GitHub (Isso você já fez ✔️)
2- Gerar uma cópia (Fork) do repositório para sua conta, utilizando a [interface do GitHub](https://docs.github.com/pt/github/getting-started-with-github/fork-a-repo)
3- Use o software git para baixar o Fork na sua máquina, [usando git clone](https://git-scm.com/docs/git-clone/pt_BR)
4- Encontre o erro dentro dos arquivos [scenes](https://github.com/lucasgcb/anxiety/tree/master/scenes) e corrija-os com seu editor de texto preferido. Salve as mudanças.
5- Use o software git para confirmar as mudanças, usando [git add](https://git-scm.com/docs/git-add/pt_BR), e empacote as mudanças usando [git commit](https://git-scm.com/docs/git-commit/pt_BR). Quando empacotar, vincule uma mensagem de commit informando o que as alterações no pacote fazem (`git commit -m "Arruma erro de digitação"`).
6- Use o software git para enviar o seu pacote de mudanças ao seu Fork no GitHub, usando [git push](https://git-scm.com/docs/git-push/pt_BR).
7- Através da interface do GitHub, abra um Pull-Request a partir do seu Fork, para o branch master do repositório do jogo.
8- Aguarde a minha aprovação de suas alterações
9- Comemore com um refresco de sua preferência 🎉

Existem alguns tutoriais em português de como realizar esse processo de contribuição, mas se ainda precisar de ajuda o ekeevo te dá uma mão.

Abraços

**Comment by GustavoOsovski** [comment]
opa eaw tranquilo?
Eu estava vendo a obra na tradução em PT-BR e encontrei um erro de Português, logo na primeira parte do jogo, na segunda linha ,está escrito "Estória" mas o certo seria "História"
.
![imagem_2021-11-28_104954](https://user-images.githubusercontent.com/72808951/143770655-e02d0424-c68e-4b30-aa40-8f082b01629e.png)
