### ISSUE TITLE
Started French Translation, help is also appreciated!

### ISSUE THREAD

**Issue by solstice-r** [ncase/anxiety#3]

**Comment by Renart-fox** [comment]
J'aimerais pouvoir aider pendant mon temps libre :)

**Comment by Feufoll** [comment]
Je pourrais aider si besoin

**Comment by elgamine-dev** [comment]
I'd be glad to give a hand !

**Comment by DPS2004** [comment]
Je peux aider

**Comment by DPS2004** [comment]
Je peux translater les images.

**Comment by DPS2004** [comment]
![callback](https://user-images.githubusercontent.com/10176105/65080902-5d83e400-d970-11e9-88c5-ba4895d7461a.png)
Voici callback.png

**Comment by Renart-fox** [comment]
> 
> 
> ![callback](https://user-images.githubusercontent.com/10176105/65080902-5d83e400-d970-11e9-88c5-ba4895d7461a.png)
> Voici callback.png

Tu devrais faire une pull request sur le fork de @NathSoM

**Comment by DPS2004** [comment]
> > ![callback](https://user-images.githubusercontent.com/10176105/65080902-5d83e400-d970-11e9-88c5-ba4895d7461a.png)
> > Voici callback.png
> 
> Tu devrais faire une pull request sur le fork de @NathSoM

https://github.com/ncase/anxiety/pull/6 J'ai fait

**Comment by DPS2004** [comment]
> > ![callback](https://user-images.githubusercontent.com/10176105/65080902-5d83e400-d970-11e9-88c5-ba4895d7461a.png)
> > Voici callback.png
> 
> Tu devrais faire une pull request sur le fork de @NathSoM

https://github.com/NathSoM/anxiety/pull/1

**Comment by angela-quidam** [comment]
Salut ☺ je veux aider ! Par contre, j'ai jamais rien compris à Github (je viens de m'inscrire pour l'occasion...)

**Comment by jyby** [comment]
> ![callback](https://user-images.githubusercontent.com/10176105/65080902-5d83e400-d970-11e9-88c5-ba4895d7461a.png)
> Voici callback.png

Je pense que "Lac des Larmes" serait plus aproprié (même si c'est plus long)?

**Comment by jyby** [comment]
I started to translate act1.md (up to  "See, human? I am your loyal guard-wolf!").
Add me as a contributors and I will push.
(I tried to attach the md file ton this comment to show my work, but got an error "We don't support that file type.")

**Comment by Feufoll** [comment]
I'm starting act2.md, can you add me as contributor ?

**Comment by NathSoM** [comment]
How do I do that @Feufoll ?

**Comment by solstice-r** [comment]
OK, jai add des contributeurs, je vais commencer a traduire aussi, jai fait le fork tard le soir et je suis revenu de l'école...

**Comment by Feufoll** [comment]
Par contre le texte original utilise des pronom neutres, on fait comment ? Je suis parti sur LE joueur et L'humain, au masculin, mais je trouve pas ça super satisfaisant...

**Comment by solstice-r** [comment]
J'ai ouvert un Discord pour chatter plus facilement vu que GitHub n'a pas de notifs bureau :/
https://discord.gg/nyrSr8p

**Comment by solstice-r** [comment]
Je sais pas, faudrait demander a @ncase ?

**Comment by Feufoll** [comment]
@jyby @angela-quidam @DPS2004 @KNaudin 
Du coup si vous pouvez tous nous rejoindre sur le discord ca sera plus simple pour s'organiser et séparer la trad
https://discord.gg/nyrSr8p

**Comment by solstice-r** [comment]
@elgamine-dev aussi

**Comment by jyby** [comment]
l'usage est d'utiliser le negatif (leS joueurS) 

On September 18, 2019 7:25:34 a.m. GMT-03:00, Feufoll <notifications@github.com> wrote:
>Par contre le texte original utilise des pronom neutres, on fait
>comment ? Je suis parti sur LE joueur et L'humain, au masculin, mais je
>trouve pas ça super satisfaisant...>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/ncase/anxiety/issues/3#issuecomment-532623321

-- 
Jérémy   (http://barbay.cl)

**Comment by solstice-r** [comment]
En passant, tu peux rejoindre le discord pour que les attributions de roles soient mieux organisées? je fais act2 la

**Comment by jyby** [comment]
ok

**Comment by Feufoll** [comment]
Hi @ncase , 
We're working on the french translation of Anxiety, as you may have seen, but there is a little gender problem going from english to french, as we don't really have a neutral way of speaking of things/people. 
So we were wondering how to translate things such as "your human", "They", wich would become either masculine or feminine. We could make everything masculine but we weren't satisfied by that, or everything feminine, wich could be a little "better" seeing how most things are masculine by default, but it still wouldn't convey the neutrality. 
Or we were thinking of using the masculine for phrases like "your human" but just because it is used to talk about animals for example, regardless of their gender, and we could use the pronoun "iel" wich is a neologism, made to be used like the english "they", but the thing is it's not sure everyone would get or appreciate that.

Do you have an opinion on this ?

**Comment by lucasgcb** [comment]
@Feufoll This also poses a problem to pretty much every other latin derived language like Spanish/Italian/Romanian/Portuguese where gender is present in nouns, so a response here would help those translations also.

**Comment by angela-quidam** [comment]
On peut utiliser l'écriture inclusive
Avec des points médians ·   (alt + 0183)
(c'était au départ utilisé par les militant·es mais ça se fait de plus en plus un peu partout)

> exemple : humain·e / roux·sse / joueur·se

**_Qui est pour ? Qui est contre ?_**

[en] We could use gender-inclusive language.
With middle dots ·
(It was initially used by activists but it is becoming more and more common everywhere.)

**Comment by tezzutezzu** [comment]
I'm finding it challenging using suffixes for nouns: we'll also need to change articles!

How would you translate: YOUR HUMAN ? 
We could use slashes (ton/ta humain/humaine), but it will soon become unreadable...

**Comment by angela-quidam** [comment]
> How would you translate: YOUR HUMAN ?(ton/ta humain/humaine)

on peut faire : _ton humain·e_
par contre oui ça pose la question du "le/la" sur d'autres mots (par exemple "joueur·se")

**Comment by tezzutezzu** [comment]
I'm trying to stay away from gendered words at the moment and use verbs as much as I can. 

For example: *shut up* should be translated with *stai zitto/a* (be quiet), but I'm translating with *taci!*  (which also mean be quiet but slighlty less colloquial)

**Comment by ncase** [comment]
Thank you all so much for helping translate! :D  Just so you know, I pushed a few more commits recently ( https://github.com/ncase/anxiety/commits/gh-pages , everything past "SHUT UP IT'S DONE"), that might slightly help with translation.

Specifically, `index.html` *actually* has notes on what to translate, there's a word-less version of the social sharing thumbnail, and the social sharing buttons can now be translated (as opposed to what it was earlier: the words directly url-encoded in the URL)

Hope that helps! :)

P.S: As for gender/pronouns, I wasn't joking when I said "flip a coin". Flip a coin!

**Comment by DominoPivot** [comment]
Yeah. It's probably safer to flip a coin instead of using neologism which are understood by very few and might distract from the message. The character's gender really doesn't matter in that story, and it's not like we have to pretend they don't have a gender.

**Comment by DPS2004** [comment]
Well i flipped some coins
Hong - female
Hunter - female
Al - male

**Comment by solstice-r** [comment]
Well we flipped more coins and we ended up on Hong being a male, but we can see whats already on the discord.

**Comment by WolfaliaZERO** [comment]
**I am interested in helping with this project !** Do we need real programming skills to help modifiyng the project ?

**Comment by solstice-r** [comment]
No, just need to know what to edit (refer to the guide ncase made)

**Comment by solstice-r** [comment]
make sure to join the discord too

**Comment by nclsppr** [comment]
Hi, I proposed my french translation of the index.html page : #35

**Comment by ncase** [comment]
Coucou à tous! (C'est la auteure de Adventures With Anxiety ici, excusez mon mauvais français) Comment ça s'est passé sur ce traduction? Si c'est pas terminé – et pas de soucis si non! – une ami d'une ami de moi, récemment, m'a offrit à traduire aussi, peut-être. Combien de mots reste?

**Comment by solstice-r** [comment]
We're almost finished, bout some help wouldnt hurt :P Also, I'm replying
from email hoping it works because i am having some issues with GitHub, I
can't login to my account. Hoping this gets resolved soon.

**Comment by Fledered** [comment]
Hi, I can help if you need !

I just need to have the translation you've done so far.

**Comment by AltoRosa** [comment]
Hi, don't know if you're close or finished yet but we (laura and me) can help translate :) we'll be joining the discord a little bit later

**Comment by Fledered** [comment]
I wish I could join the discord, but the invite link expired. Could someone send me another one please ?

**Comment by solstice-r** [comment]
here's the link https://discord.gg/xDZAaT5

**Comment by Fledered** [comment]
It doesn't work either : 
![2020-01-21 10_45_45-Traduction de AwA](https://user-images.githubusercontent.com/52155944/72793827-3c434500-3c3b-11ea-8436-e7023f87f6b5.png)

**Comment by solstice-r** [comment]
essaye en navigation privée ?

**Comment by Fledered** [comment]
It works ! Thanks !

**Comment by LukasOchiwo** [comment]
Bonjour ! J'ai récemment découvert le jeu et je voudrai apporter mon aide au projet (qui a l'air un peu en stand-bye pour l'instant). C'est la première fois que je fais ce genre de choses et j'espère pouvoir me rendre utile.

**Comment by solstice-r** [comment]
Cool, rejoins le discord et ping moi demain, je te mettrais contributeur sur le repoSent from my Samsung Galaxy smartphone.
-------- Original message --------From: LukasOchiwo <notifications@github.com> Date: 29/03/2020  21:47  (GMT+01:00) To: ncase/anxiety <anxiety@noreply.github.com> Cc: NathSoM <nathsom.r05@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [ncase/anxiety] Started French Translation, help is also appreciated! (#3) 

Bonjour ! J'ai récemment découvert le jeu et je voudrai apporter mon aide au projet (qui a l'air un peu en stand-bye pour l'instant). C'est la première fois que je fais ce genre de choses et j'espère pouvoir me rendre utile.

**Comment by giantjack** [comment]
Je viens de découvrir le jeu, et c'est tellement d'utilité publique qu'il FAUT que ce soit dispo en français. J'aurais tellement aimé y avoir accès il y a 10 ans.
Un immense MERCI à ncase pour avoir fait ça :)

Où en est-on et que reste-t-il à faire précisément ?

**Comment by solstice-r** [comment]
Il y a toutes les Infos sur le discord:https://discord.gg/xDZAaT5Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: giantjack <notifications@github.com> Date: 25/05/2020  14:23  (GMT+01:00) To: ncase/anxiety <anxiety@noreply.github.com> Cc: NathSoM <nathsom.r05@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [ncase/anxiety] Started French Translation, help is also appreciated! (#3) 

Je viens de découvrir le jeu, et c'est tellement d'utilité publique qu'il FAUT que ce soit dispo en français. J'aurais tellement aimé y avoir accès il y a 10 ans.

Un immense MERCI à ncase pour avoir fait ça :)

Où en est-on et que reste-t-il à faire précisément ?



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ncase/anxiety/issues/3#issuecomment-633546216",

"url": "https://github.com/ncase/anxiety/issues/3#issuecomment-633546216",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by giantjack** [comment]
Ca me dit "invitation invalide" :/

**Comment by Mintech0** [comment]
J'aimerais bien aidé! J'ai 3 semaines de libre et j'appuie le fait que ce jeu devrait être traduit pour le rendre le plus accessible possible!

**Comment by thief-sty** [comment]
On a fini !
https://nathsom.github.io/ncase-anxiety/

<3

**Comment by Algorythmis** [comment]
@ncase (sorry for pinging you everywhere lol) you might want to close this issue?

**Comment by lucasgcb** [comment]
Why was this closed voluntarily? 
You're meant to ping @ncase so they can look at it.
