### ISSUE TITLE
European Spanish translation [COMPLETE!]

### ISSUE THREAD

**Issue by JorgeyGari** [ncase/anxiety#36]
I know there's already a Latin Spanish translation in progress, but a European Spanish translation will use typical expressions from Spain and will sound more natural to Spaniards.

[https://github.com/JorgeyGari/anxiety](url)

**Comment by JorgeyGari** [comment]
**Act 1 - COMPLETE!**

**Comment by JorgeyGari** [comment]
**Act 2 - COMPLETE!**

**Comment by JorgeyGari** [comment]
**Act 3 - COMPLETE!**

**Comment by JorgeyGari** [comment]
**Act 4 - COMPLETE!**

**Comment by fantasmashy** [comment]
Oh, está bien tener ambas versiones y ¡Santo cielo! ¡¿Acabaste en tres días?!

**Comment by JorgeyGari** [comment]
Je, je, sí. Tenía muchas ganas de este proyecto. A lo largo de la semana intentaré hacer la edición de las imágenes y la revisión final de los textos.
¡Mucha suerte con la versión latina, por cierto!

**Comment by JorgeyGari** [comment]
**Graphics - COMPLETE!**

**Comment by JorgeyGari** [comment]
Okay, the site is now up and running, but the translation isn't done yet, I still have to playtest it and check for errors or graphical glitches.

**Comment by IagoParis** [comment]
Hello, JorgeyGari. I entered this post expecting a barely started translation so I'm amazed at your progress! I feel so grateful that the very least I can't do is to offer myself to playtest alongside you! You up to it?

**Comment by IagoParis** [comment]
Well, I already did. Found myself stuck after the cat GIF. I will wait for your answer better.
Thanks for your work again

**Comment by JorgeyGari** [comment]
Hi, IagoParis!
Thank you so much both for your kind words and for playtesting!
Yeah, there’s some softlocks in the game due to me accidentally deleting some blank lines like an idiot, haha. Luckily for me, they’re easy to hunt down and fix, so I think by this weekend I’ll have finished polishing everything. But yeah, in its current state, you’ll have to get lucky to finish the game.
I’ll ping you when I finish fixing those softlocks so you can playtest properly.
Really, thank you for your feedback!

**Comment by JorgeyGari** [comment]
I did get to finish one of my playthroughs, I think I chose white bread, decline the invitation and news story. Then in the party I chose ignoring. And finally I jumped off the roof.
There were still some bugs but they only caused some missing dialogue. I was able to watch the credits roll.

**Comment by IagoParis** [comment]
Hi again. Aside from the blocker bug, I did screenshots of the dialogue glitches and other things. If you wish, I propose you to organize ourselves to playtest the game when you are over. Something like you do all first choices, I do all second choices and any of us the third ones. At your disposal :)

**Comment by JorgeyGari** [comment]
**The translation is now complete!** I'll try to contact Nicky soon.

**Playtesters welcome!** Please report all glitches, mistranslations, grammatical or spelling errors, the works.
**¡Testeadores, bienvenidos!** Por favor, reportad todos los errores de programación, traducción, gramaticales u ortográficos, y todo eso.

@IagoParis 
I'm going to try and organize every option in the game in a flowchart so we can work on this more easily. In the meantime, playtest to your heart's content!
Thank you so much, again!

**Comment by hanekDaikaen** [comment]
Ok, then i will begin testing bottom-up, all-third-choices then all-second-choices then all-first-choices, without haste. Talk to you soon.

**Comment by IagoParis** [comment]
Ok, then i will begin testing bottom-up, all-third-choices then all-second-choices then all-first-choices, without haste. Talk to you soon.

**Comment by IagoParis** [comment]
Here all third-choices as screenshots: https://my.pcloud.com/publink/show?code=kZgjKQkZ7qKxf5jj4VpVpzdjbeozVfBKVqgy
Feel free to ignore every suggestion that you don't find fitting (I may like commas a bit)
I will be update that folder and this thread when I playtest another choice set.
Thank you :)

**Comment by IagoParis** [comment]
By the way, here is the link to directly **playtest** this Spanish version:
[https://jorgeygari.github.io/anxiety/](https://jorgeygari.github.io/anxiety/)
It may be a bit difficult to find since clicking the link at the top don't go to your fork, @JorgeyGari. I hope I didn't overstep.

**Comment by IagoParis** [comment]
Second choices revised

**Comment by fantasmashy** [comment]
Creo que ya terminé con mi versión, las estaba testeando a ambas al mismo tiempo, es divertido hacer la comparación.

Primero, esto.
![ans1](https://user-images.githubusercontent.com/49044996/69001784-e066e380-08ba-11ea-94b8-71194fa5d2c8.png)


Pequeño error~
![ans 3](https://user-images.githubusercontent.com/49044996/69002925-465d6600-08cf-11ea-917c-5ff90fe816a3.png)


Gran error~
![ans 4](https://user-images.githubusercontent.com/49044996/69002971-64779600-08d0-11ea-912a-40ee0ca398b9.png)


Y no se si esto está mal o no. No se entiende bien.
![ans2](https://user-images.githubusercontent.com/49044996/69001791-12784580-08bb-11ea-8493-1b79d6ae27ea.png)

Eso es todo.

**Comment by JorgeyGari** [comment]
@IagoParis ¡Gracias por publicar el enlace!

@fantasmashy ¡Enhorabuena por completar tu traducción y muchas gracias por reportar esos errores! Eso de jugar con las dos versiones a la vez suena interesante, tal vez lo pruebe :P

**Comment by JorgeyGari** [comment]
**GREAT NEWS!** - The European Spanish localization of Adventures with Anxiety is now **officially finished!**
I just got a reply from Nicky saying they'll post a link to the translation in the next few days.
Thank you all for your support! Especially @IagoParis, who helped me playtest.

**Comment by hanekDaikaen** [comment]
First choices revised. Just four screenshots :)
You're welcome, @JorgeyGari, it has been great to work with you!

**Comment by IagoParis** [comment]
First choices revised. Just four screenshots :)
You're welcome, @JorgeyGari, it has been great to work with you!
