### ISSUE TITLE
Flowchart for playtesters!

### ISSUE THREAD

**Issue by JorgeyGari** [ncase/anxiety#37]
Hi! I’ve attempted to make a flowchart to make playtesting a bit easier. Please keep in mind this was done during a playthrough and with little care, but it may come handy either way. Still, excuse me if some choices are missing!

Here it is:
[Google Drive](https://drive.google.com/file/d/1SQBEjdnSGh_M3cNOOQGQFio7DVXR29oH/view?usp=sharing)
[PDF File](https://github.com/ncase/anxiety/files/8904169/Adventures.with.Anxiety.Flowchart.pdf)

**Comment by ncase** [comment]
This is beautiful! Thank you for this! 😄

**Comment by IagoParis** [comment]
Yes it is! Thank you
