### ISSUE TITLE
Bahasa Indonesia Translation

### ISSUE THREAD

**Issue by ganiaaldi** [ncase/anxiety#45]
Hello, im starting to translation this project into Indonesian language.
Feel free to join contributing in this translation project :) 

here's the link for fork the project :
https://github.com/ganiaaldi/anxiety

to see progress : 
https://ganiaaldi.github.io/anxiety/

**Comment by ganiaaldi** [comment]
all pictures already finished.
act2 work in progress.

**Comment by ganiaaldi** [comment]
finished

**Comment by palingdisitalagi** [comment]
Hi there. I would like to know if I can contribute in translating in any way. Please let me know if I can help. Thank you.
