### ISSUE TITLE
Thai Translation

### ISSUE THREAD

**Issue by RamBanjo** [ncase/anxiety#55]
[https://github.com/RamBanjo/anxiety](https://github.com/RamBanjo/anxiety)

Hi, I'm attempting a Thai translation!

**Comment by sunbao1553** [comment]
ค้างอยู่หน้า กำลังโหลด นะท่าน u ^u

**Comment by RamBanjo** [comment]
> ค้างอยู่หน้า กำลังโหลด นะท่าน u ^u

อันนี้เปิดจากหน้า https://rambanjo.github.io/anxiety/ หรือเปล่าครับ หรือว่าโหลด repo บน desktop ถ้าอย่างหลังมันจะค้าง
