### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by Grapto** [ncase/anxiety#63]
https://github.com/Grapto/anxiety.git

Вітаю усіх хто це читає!

Я рішила перекласти цю роботу для своєї практики. 
У мене є бажання поширювати свою мову та збільшувати для нас можливості. Хоч це і маленький вклад, але я буду щасливою,  якщо людина зможе знайти українську серед інших мов.

Відкрита для допомоги. Можуть бути граматичні помилки/суржик. Надіюсь знайдуться люди, які мені з цим допоможуть та покращуть цю роботу.

Акт 1+2+3+4 перекладено! (редагуються)
Світлини перекладені.
Окей, робота закінчена та опублікована)))

**Comment by Grapto** [comment]
> https://github.com/Grapto/anxiety.git
> 
> Вітаю усіх хто це читає!
> 
> Я рішила перекласти цю роботу для своєї практики. У мене є бажання поширювати свою мову та збільшувати для нас можливості. Хоч це і маленький вклад, але я буду щасливою, якщо людина зможе знайти українську серед інших мов.
> 
> Відкрита для допомоги. Можуть бути граматичні помилки/суржик. Надіюсь знайдуться люди, які мені з цим допоможуть та покращуть цю роботу.
> 
> Акт 1, 2 перекладено!

**Comment by sw1ftrr** [comment]
Привіт! Чи міг би я допомогти з перекладом?

**Comment by Grapto** [comment]
Вітаю!! Я можу Вам відправити перекладені акти для перевірки на помилки. Або можете поклінити арти. Що більше до вподоби?

**Comment by sw1ftrr** [comment]
Можу перевірити вже перекладене :)

**Comment by Grapto** [comment]
О, як буде можливість дам одразу. Куди Вам зручніше перекинути файли?

**Comment by sw1ftrr** [comment]
Можна було б на Діскорд, Swiftbed Netherman#8601
