### ISSUE TITLE
Mention to check for existing forks before starting a new (translation) fork

### ISSUE THREAD

**Issue by jyby** [ncase/anxiety#9]
It sounds obvious, but many other less obvious stuff are mentioned, so...

Edit  https://github.com/ncase/anxiety#how-to-translate to mention 
"Step 0: check in the "Issues" for an existing fork indicating that someone already started to translate in the language you are interested in"

**Comment by ncase** [comment]
Resolved! https://github.com/ncase/anxiety/pull/28
